### ISSUE TITLE
No main class detected.

### ISSUE THREAD

**Issue by khajavi** [coreyauger/surfkit#1]
Here is the output, when I run `sbt run`:

```
[info] Loading global plugins from /home/milad/.sbt/0.13/plugins
[info] Loading project definition from /home/milad/tmp/surfkit/project
[info] Loading project definition from /home/milad/tmp/scalajs-google-maps/project
[info] Set current project to surfkit (in build file:/home/milad/tmp/surfkit/)
java.lang.RuntimeException: No main class detected.
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last root/compile:run for the full output.
[error] (root/compile:run) No main class detected.
[error] Total time: 0 s, completed Dec 2, 2015 6:47:46 PM
```

How can I run the project?

**Comment by coreyauger** [comment]
It has been a while since I have updated the project.  I plan to do that in the next month or so.  This will replace dependencies on `neo4j` and `postgres` with `cassandra`

However to answer your question.. the build.sbt contains a number of `subprojects`.  You will need at minimum:
- to be running rabbitMQ on the host
- running postgres and neo4j (again these will be going away)

Once these are running you can start the sub projects:
- in console 1: `sbt 'project core' run`
- console 1: `sbt 'project hangten' run`
- then in another console you can run the web project `sbt` then `project web` then `~run`

I plan on giving this project some more attention in the near future.  Thanks.

**Comment by khajavi** [comment]
Thank you, now I can run the project.
